using System.Collections.Generic;
using WowGd.Src.Entities;

namespace WowGd.Src.Combat.Abilities.Exp.Targeting.Payload;


/// <summary>
/// Represents the payload resulting of a targeting query.
/// The launcher is the entity at the initiative of the target query, typically of the spell launch.
/// 
/// This entity might appear twice - if the targeting query used an area.
/// It might then be included in the `_targets`. 
/// </summary>
/// <param name="targets">The resulting targets of the query.</param>
/// <param name="launcher">The entity at the initiative of the target query.</param>
/// <param name="actuateWeight">A weight generated by the spell's actuator. For example, some typing accuracy modifier.</param>
public readonly struct TargetsPayload(Target[] targets, IEntity launcher, float actuateWeight)
{
    private readonly Target[] _targets = targets;
    public readonly IEntity Launcher = launcher;
    public readonly IReadOnlyList<Target> Targets => _targets;
    /// <summary>
    /// A weight generated by the spell's actuator.
    /// 
    /// For example, it could correspond to some kind of accuracy calculation, speed, etc.
    /// How this weight has been obtained cannot be known anymore, it should just be interpreted as what it is - a weight.
    /// </summary>
    public readonly float ActuateWeight = actuateWeight;
}