using WowGd.Src.Entities;

namespace WowGd.Src.Combat.Abilities.Targeting.Payload;

/// <summary>
/// Represents a target, resulting of a targeting query.
/// </summary>
/// <param name="entity">The targeted entity.</param>
/// <param name="relation">
/// The relation this target has to the query launcher (see TargetsPayload.Launcher).
/// This typically abstracts away `TeamMask` relations as a much more straight forward, "side agnostic", and functionnal data.
/// </param>
/// <param name="isDirect">
/// Whether the target results from an indirect area or explicit targeting.
/// </param>
/// <param name="gatherWeight">
/// A weight generated by the effect's gatherer. For example, some distance fall off.
/// </param>
public readonly struct Target(IEntity entity, TargetRelation relation, bool isDirect, float gatherWeight)
{
    public readonly IEntity         Entity       = entity;
    public readonly TargetRelation  Relation     = relation;
    public readonly bool            IsDirect     = isDirect;
    /// <summary>
    /// A weight generated by the effect's gatherer.
    /// 
    /// For example, it could correspond to distance fall off, a chaining light ability that does less and less damage on each chained target, etc.
    /// How this weight has been obtained cannot be known anymore, it should just be interpreted as what it is - a weight.
    /// </summary>
    public readonly float           GatherWeight = gatherWeight;
}